### PR TITLE
🔥 Remove unused overflow error from osmosis swap adapter

### LINKED ISSUE #12: Oak Security Audit - Finding 10

### PR DESCRIPTION
**Pull request by NotJeremyLiu**
Closes #12 

This PR removes an unused overflow error.

### CODE REVIEW

**Comment by jaybxyz** [comment]
It looks like it is partially resolved. Is there any reason why remaining other unused errors?

**Comment by NotJeremyLiu** [comment]
> It looks like it is partially resolved. Is there any reason why remaining other unused errors?

@jaybxyz the other errors pointed out in the audit findings are used, this can be verified by commenting any of them out and trying to compile the contracts.

**Comment by jaybxyz** [comment]
@NotJeremyLiu Thanks! you're right. I can verify that the other pointed out unused errors are false positive. We will remove them in the report.

**Review by jaybxyz — APPROVED** [review]

**Comment by NotJeremyLiu** [comment]
> @NotJeremyLiu Thanks! you're right. I can verify that the other pointed out unused errors are false positive. We will remove them in the report. Let's wait until other auditors have this double-checked.

@jaybxyz Just flagging for your awareness, I shared a google doc with @cfkelly18 that gives a response / explanation for all the findings that I view as context / backgrounds to the PRs. I did not want to make that public since the report is in draft state, but reading through that while reviewing the PRs will help a ton!

**Comment by jaybxyz** [comment]
@NotJeremyLiu Yeah, i am looking at the google doc that is shared with us but I did not pay attention to the explanation at the bottom of the document. I can see them now and i will reference them. Thanks for providing the context and backgrounds to the PRs 👍  It is very helpful and convenient for us to review.

**Pull request merged**
